- name: Install packages
  apt:
    name: "{{ ubuntu_packages }}"
    state: present
    update_cache: yes

- name: Download WordPress (tar.gz version)
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Apply WordPress config
  template:
    src: ../../templates/wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: Apply nginx config
  template:
    src: ../../templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Reload nginx
  service:
    name: nginx
    state: restarted